# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b56b7a5d58fed0a87cddf8e04c72d889"
name = "Affiliate-Saleshq"
application_url = "https://affiliateapp.saleshq.ai"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"
[[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
topics = [ "orders/paid" ]
uri = "/webhooks/orders/paid"

[[webhooks.subscriptions]]
topics = [ "orders/updated" ]
uri = "/webhooks/orders/updated"

[[webhooks.subscriptions]]
topics = [ "orders/cancelled" ]
uri = "/webhooks/orders/cancelled"

[[webhooks.subscriptions]]
topics = [ "refunds/create" ]
uri = "/webhooks/refunds/create"

[[webhooks.subscriptions]]
topics = [ "fulfillments/create" ]
uri = "/webhooks/fulfillments/create"

[[webhooks.subscriptions]]
topics = [ "fulfillments/update" ]
uri = "/webhooks/fulfillments/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_orders,write_products,write_discounts,read_discounts,write_price_rules,read_price_rules,write_pixels,read_customer_events"

[auth]
redirect_urls = [ "https://affiliateapp.saleshq.ai/auth/callback" ]

[capabilities]
customer_events = true
