# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66dfda448380dd1a52e37fa5166d8067"
name = "SalesHq-App"
application_url = "https://affiliateapp.saleshq.ai"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "https://asia-south1-touch-17fa9.cloudfunctions.net/shopifyOrderCreated"

[[webhooks.subscriptions]]
topics = [ "orders/updated" ]
uri = "https://shopifyordercancelled-dkhjjaxofq-el.a.run.app"

[[webhooks.subscriptions]]
topics = [ "orders/cancelled" ]
uri = "https://shopifyordercancelled-dkhjjaxofq-el.a.run.app"

[[webhooks.subscriptions]]
topics = [ "refunds/create" ]
uri = "https://shopifyrefundcreated-dkhjjaxofq-el.a.run.app"


  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_orders,write_products,write_discounts,read_discounts,write_price_rules,read_price_rules,write_pixels,read_customer_events"

[auth]
redirect_urls = [ "https://affiliateapp.saleshq.ai/auth/callback" ]

[capabilities]
customer_events = true
